name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  stylua:
    name: Stylua format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Stylua in check mode
        uses: JohnnyMorganz/stylua-action@v3
        with:
          version: 0.20.0
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check .

  luacheck:
    name: Luacheck lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Lua + LuaRocks
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "luajit"
      - name: Install luacheck via LuaRocks
        run: luarocks install luacheck
      - name: Run luacheck
        run: luacheck . --config .luacheckrc --codes --ranges